{% set name = "zdaemon" %}
{% set version = "4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zdaemon-{{ version }}.tar.gz
  sha256: f249fc6885646d165d7d6b228a7b71f5170fc7117de9e0688271f8fb97840f72

build:
  number: 1003
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - zdaemon=zdaemon.zdctl:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools
    - zconfig

test:
  imports:
    - zdaemon
    - zdaemon.tests
  commands:
    - zdaemon --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zopefoundation/zdaemon
  summary: Daemon process control library and tools for Unix-based systems
  license: ZPL-2.1
  license_file: COPYRIGHT.txt

about:
  home: https://github.com/zopefoundation/zdaemon
  license_file: LICENSE.txt
  license: ZPL 2.1
  license_family: OTHER
  summary: 'Daemon process control library and tools for Unix-based systems'
  dev_url: https://github.com/zopefoundation/zdaemon
  doc_url: https://github.com/zopefoundation/zdaemon

extra:
  recipe-maintainers:
    - pmlandwehr
