# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "GOiWfVUC5AoVrF5QQE/8PGSQRXrHxi8sIk9lvusOGYvtNeFISgnqGN6ZxuOfRqZtYbW3EQYxWU3Niwx8MiF+mFOVN//n/dmHRiOp4e9iTMJHDGIRa0hYM8aaj57D3Zy9v6b8QzkW026r3ErI657cPJv/qXJFF8zvcBJCWn6rC3Ghu2tYHBoxl1M24PRquVlJTcXnERTdCQH0CrFD/3C1Iv92VXdBOy/OuBYPMEm07KYutsxxL4kbfinbF4EEvwbz/7zgCaC1Su0JCQgEF/gtcUBl4fpb/NRpedpF+5/15UMMy+pdsdDMIvp4u9gjIW45G9fPhBs3KMKCc/Bas4FRULvleu6vB60GuJ9Tg6Fjhobor6mWKDdRQr5NsoGPwnzaWW2s8AOqMjxWndABgjw8sxmXQ4mPhWW+mTNbsW2QHWznjops1FmXccSMbHDZrx/LI9BCOSjlBRWa+9oDd3T7QVBnToQKuu8pb0/gYxqL7OWDrB1WfSUFOyzp+tZeKllKZCfR+9N5JwT8iGBphGbw2g9KLD2tgJWzuPBUaKkNQ2Hf+Z8JaatuMYssVvy7rJ2LHj02P2YHt+88beS0oeNTL5bVXesF65x6Uh0PyF6jaJgkgnXuwZqA3IEenCZMXz4/SlEwcsnPl3g1FZqHDbfyu097kctHqo8LaEdo5UboFf0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
