appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: TRE31PZOCl4lVY+cUqLes6YMHMik6HhX7DJE4k532M+1DyBYAd6Z3JJzS1Jx50ktALJ+OaM67bSNB1CjWY3Hc3O4Ac53cV8PVjmhl2PJYCcKWskfy3O1rimaMQrds9t2OEHW2CVxA6ilo8M/t2LzTdnG1cc4+Yz6xwnKTfRODBCr8TPcq3bk54w4WZuk8ASMIkOsFkP2R08QhXUAj5LXtJknfRm5b/JeucoBI0s0pG83PnoMjNIRUDBvFV2e6y/lshBFeAxDu91+HIWXw0rSEeHEU7Og6kdNRQI/sklx7nW7GDtiop+REgs0kuwPJ3gx43meWegEpI+A5jDPoKjM6g0CyhyMDr2DwNk0pLHzk2DHj+qUlHnqtLp6NHzH6bcxhf66wgbWa2RTQ8RSweQJ+sWYxlRDJh67Z2oQLSY84KO2f5pLeNuFkVDFa08J2UsPxWuoF5ssRioZC4t0O6ZDTMHlH0cvbBG1ycSPkZwYruNx7GljEdcjkDgDRPufmR7sSzJPKT7/p+auuFiT3FHFLW3medNLtLKl31DpayKTPc9g76Xu7ddU5X5IDiGRSkkRWw/1ZSix5her87WkfqtJOVkm551AuFcT8QZ7s1DmmAbVDDFTkg+k4cjN5BGApWxqjeCkdVSVLeZLGxWJXoP9oMzj35kbTlpVBSt1WbIR3Vg=}
provider:
  win: azure
conda_forge_output_validation: true
