travis:
  secure:
    BINSTAR_TOKEN: GOiWfVUC5AoVrF5QQE/8PGSQRXrHxi8sIk9lvusOGYvtNeFISgnqGN6ZxuOfRqZtYbW3EQYxWU3Niwx8MiF+mFOVN//n/dmHRiOp4e9iTMJHDGIRa0hYM8aaj57D3Zy9v6b8QzkW026r3ErI657cPJv/qXJFF8zvcBJCWn6rC3Ghu2tYHBoxl1M24PRquVlJTcXnERTdCQH0CrFD/3C1Iv92VXdBOy/OuBYPMEm07KYutsxxL4kbfinbF4EEvwbz/7zgCaC1Su0JCQgEF/gtcUBl4fpb/NRpedpF+5/15UMMy+pdsdDMIvp4u9gjIW45G9fPhBs3KMKCc/Bas4FRULvleu6vB60GuJ9Tg6Fjhobor6mWKDdRQr5NsoGPwnzaWW2s8AOqMjxWndABgjw8sxmXQ4mPhWW+mTNbsW2QHWznjops1FmXccSMbHDZrx/LI9BCOSjlBRWa+9oDd3T7QVBnToQKuu8pb0/gYxqL7OWDrB1WfSUFOyzp+tZeKllKZCfR+9N5JwT8iGBphGbw2g9KLD2tgJWzuPBUaKkNQ2Hf+Z8JaatuMYssVvy7rJ2LHj02P2YHt+88beS0oeNTL5bVXesF65x6Uh0PyF6jaJgkgnXuwZqA3IEenCZMXz4/SlEwcsnPl3g1FZqHDbfyu097kctHqo8LaEdo5UboFf0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
